# 未填的采用默认值

APP:
  NAME: gin_bbs
  RUNMODE: debug # 模式: debug, release, test
  Addr: :8889 # 端口
  URL: http://localhost:8889 # 网站 url，内部跳转时会用到该项
  KEY: base64:O+VQ74YEigLPDzLKnh2HW/yjCdU2ON9v7xuKBgSOEAo=
  ENABLE_CSRF: true # 是否开启 csrf

DB:
  CONNECTION: mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: gin_bbs
  USERNAME: wutong
  PASSWORD: secret

MAIL:
  MAIL_DRIVER: smtp # smtp or log (smtp: 使用支持 ESMTP 的 SMTP 服务器发送邮件，log: 适用于调试，会将邮件内容写入 log 中)
  MAIL_HOST: smtp.mailtrap.io # 邮箱的 SMTP 服务器地址
  MAIL_PORT: 2525 # 邮箱的 SMTP 服务器端口
  MAIL_USERNAME:
  MAIL_PASSWORD: # 授权码或密码
  MAIL_FROM_NAME: gin_bbs # 用来作为邮件的发送者名称

LOG:
  WRITERS: file,stdout # 输出位置，有两个可选项 —— file 和 stdout。选择 file 会将日志记录到 logger_file 指定的日志文件中，选择 stdout 会将日志输出到标准输出，当然也可以两者同时选择
  LOGGER_LEVEL: DEBUG # 日志级别，DEBUG、INFO、WARN、ERROR、FATAL
  LOGGER_FILE: storage/logs/gin_bbs.log # 日志文件
  LOG_FORMAT_TEXT: false # 日志的输出格式，JSON 或者 plaintext，true 会输出成 JSON 格式，false 会输出成非 JSON 格式
  ROLLING_POLICY: size # rotate 依据，可选的有 daily 和 size。如果选 daily 则根据天进行转存，如果是 size 则根据大小进行转存
  LOG_ROTATE_DATE: 1 # rotate 转存时间，配 合rollingPolicy: daily 使用
  LOG_ROTATE_SIZE: 1 # rotate 转存大小，配合 rollingPolicy: size 使用 (大于 1mb 会压缩为 zip)
  LOG_BACKUP_COUNT: 7 # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数

# 百度翻译
BAIDU_TRANSLATE:
  APPID:
  KEY:
